### ISSUE TITLE
Cannot make it work

### ISSUE THREAD

**Issue by varadero** [GoodPHP/grapesjs-plugin-ckeditor5#5]
I am following README.md and I have the following index.html:

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Ckeditor5</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link href="assets/grapes.min.css" rel="stylesheet">
  <script src="assets/grapes.min.js"></script>
  <script src="assets/grapesjs-preset-webpage.min.js"></script>
  <link href="assets/grapesjs-preset-webpage.min.css" rel="stylesheet">
  <script src="assets/ckeditor5.js"></script>
  <script src="assets/grapesjs-plugin-ckeditor5.min.js"></script>
</head>
<body>
  <div id="gjs">
  </div>

  <script type="text/javascript">
    var editor = grapesjs.init({
        container : '#gjs',
        plugins: ['gjs-plugin-ckeditor5'],
        pluginsOpts: {
          'gjs-plugin-ckeditor5': {
              position: 'left',
              options: {
                trackChanges: {},
                toolbar: {
                  items: [
                    'heading',
                    '|',
                    'fontColor',
                    'fontSize',
                    'fontFamily',
                    'fontBackgroundColor',
                    'alignment',
                    'bold',
                    'italic',
                    'underline',
                    'strikethrough',
                    'link',
                    'bulletedList',
                    'numberedList',
                    'horizontalLine',
                    '|',
                    'outdent',
                    'indent',
                    '|',
                    'blockQuote',
                    'insertTable',
                    '|',
                    'undo',
                    'redo'
                  ]
                },
                language: 'en',
                table: {
                  contentToolbar: [
                    'tableColumn',
                    'tableRow',
                    'mergeTableCells',
                    'tableCellProperties',
                    'tableProperties'
                  ]
                },
                licenseKey: ''
              }
            }
        }
    });
  </script>
  <app-root></app-root>
</body>
</html>
```

But when I load it, I get console error:
```
Uncaught ReferenceError: ClassicEditor is not defined
    at grapesjs-plugin-ckeditor5.min.js:2:8361
    at grapes.min.js:2:676285
    at Array.forEach (<anonymous>)
    at Object.init (grapes.min.js:2:676122)
    at (index):21:27
```

The versions that I have installed and put in the `assets` folder (to load them from `index.html` following the README.md):
```
    "grapesjs": "0.18.2",
    "grapesjs-plugin-ckeditor5": "0.0.33",
    "grapesjs-preset-webpage": "^0.1.11",
```

This plugin is also missing guidance on how to use it when installed as package from `npm (with `import 'grapesjs-plugin-ckeditor5'`).

**Comment by GoodPHP** [comment]
Your creditor5 ( <script src="assets/ckeditor5.js"></script> ) should be pack of ClassicEditor.

Example:
https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html

**Comment by varadero** [comment]
Well, I am using the one from this repository assuming it is the correct one:

https://github.com/GoodPHP/grapesjs-plugin-ckeditor5/tree/master/ckeditor5/build

**Comment by GoodPHP** [comment]
Can you contact with me on email and show me your project?
support@devfuture.pro
